2024-03-28 20:24:06,889 - INFO - Found credentials from IAM Role: treefolio-sylvania-ec2
2024-03-28 20:24:16,403 - INFO - Start processing tile_id 12245
2024-03-28 20:29:23,943 - INFO - New GeoJSON for tile_id 12245 saved
2024-03-28 20:29:24,768 - INFO - Start processing tile_id 7165
2024-03-28 20:33:06,140 - INFO - New GeoJSON for tile_id 7165 saved
2024-03-28 20:33:06,918 - INFO - Start processing tile_id 52162
2024-03-28 20:34:35,728 - ERROR - Error processing tile_id: 52162. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-28 20:34:35,981 - INFO - Start processing tile_id 32232
2024-03-28 20:34:36,040 - INFO - Lidar Json data does not exist for tile 32232 in year 2017
2024-03-28 20:34:36,041 - INFO - Start processing tile_id 977165
2024-03-28 20:39:46,014 - INFO - New GeoJSON for tile_id 977165 saved
2024-03-28 20:39:46,696 - INFO - Start processing tile_id 937130
2024-03-28 20:42:26,236 - INFO - New GeoJSON for tile_id 937130 saved
2024-03-28 20:42:26,669 - INFO - Start processing tile_id 210
2024-03-28 20:47:32,483 - INFO - New GeoJSON for tile_id 210 saved
2024-03-28 20:47:33,502 - INFO - Start processing tile_id 37152
2024-03-28 20:49:37,527 - INFO - New GeoJSON for tile_id 37152 saved
2024-03-28 20:49:37,784 - INFO - Start processing tile_id 45230
2024-03-28 20:49:37,887 - INFO - Lidar Json data does not exist for tile 45230 in year 2017
2024-03-28 20:49:37,888 - INFO - Start processing tile_id 930147
2024-03-28 20:49:37,905 - INFO - Lidar Json data does not exist for tile 930147 in year 2017
2024-03-28 20:49:37,905 - INFO - Start processing tile_id 945130
2024-03-28 20:49:37,920 - INFO - Lidar Json data does not exist for tile 945130 in year 2017
2024-03-28 20:49:37,920 - INFO - Start processing tile_id 45227
2024-03-28 20:56:24,733 - ERROR - Error processing tile_id: 45227. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-28 20:56:25,329 - INFO - Start processing tile_id 42175
2024-03-28 20:57:04,649 - ERROR - Error processing tile_id: 42175. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-28 20:57:04,744 - INFO - Start processing tile_id 17152
2024-03-28 20:57:43,676 - ERROR - Error processing tile_id: 17152. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-28 20:57:43,798 - INFO - Start processing tile_id 32172
2024-03-28 20:58:18,764 - ERROR - Error processing tile_id: 32172. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-28 20:58:18,882 - INFO - Start processing tile_id 7147
2024-03-28 20:58:18,939 - INFO - Lidar Json data does not exist for tile 7147 in year 2017
2024-03-28 20:58:18,939 - INFO - Start processing tile_id 965155
2024-03-28 21:02:28,360 - INFO - New GeoJSON for tile_id 965155 saved
2024-03-28 21:02:28,995 - INFO - Start processing tile_id 27160
2024-03-28 21:02:29,060 - INFO - Lidar Json data does not exist for tile 27160 in year 2017
2024-03-28 21:02:29,061 - INFO - Start processing tile_id 947135
2024-03-28 21:04:03,500 - ERROR - Error processing tile_id: 947135. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-28 21:04:04,024 - INFO - Start processing tile_id 30245
2024-03-28 21:08:54,417 - INFO - New GeoJSON for tile_id 30245 saved
2024-03-28 21:08:55,018 - INFO - Start processing tile_id 57180
2024-03-28 21:14:17,341 - INFO - New GeoJSON for tile_id 57180 saved
2024-03-28 21:14:17,924 - INFO - Start processing tile_id 17230
2024-03-28 21:15:30,473 - INFO - New GeoJSON for tile_id 17230 saved
2024-03-28 21:15:30,651 - INFO - Start processing tile_id 40187
2024-03-28 21:21:47,900 - INFO - New GeoJSON for tile_id 40187 saved
2024-03-28 21:21:48,630 - INFO - Start processing tile_id 997162
2024-03-28 21:28:34,721 - INFO - New GeoJSON for tile_id 997162 saved
2024-03-28 21:28:35,528 - INFO - Start processing tile_id 980172
2024-03-28 21:34:15,551 - INFO - New GeoJSON for tile_id 980172 saved
2024-03-28 21:34:16,157 - INFO - Start processing tile_id 977177
2024-03-28 21:35:22,790 - INFO - New GeoJSON for tile_id 977177 saved
2024-03-28 21:35:23,148 - INFO - Start processing tile_id 50190
2024-03-28 21:40:01,625 - INFO - New GeoJSON for tile_id 50190 saved
2024-03-28 21:40:02,303 - INFO - Start processing tile_id 942145
2024-03-28 21:43:43,005 - INFO - New GeoJSON for tile_id 942145 saved
2024-03-28 21:43:43,817 - INFO - Start processing tile_id 60212
2024-03-28 21:51:12,328 - INFO - New GeoJSON for tile_id 60212 saved
2024-03-28 21:51:13,205 - INFO - Start processing tile_id 937157
2024-03-28 21:56:44,603 - INFO - New GeoJSON for tile_id 937157 saved
2024-03-28 21:56:45,770 - INFO - Start processing tile_id 932172
2024-03-28 21:58:21,614 - INFO - New GeoJSON for tile_id 932172 saved
2024-03-28 21:58:21,952 - INFO - Start processing tile_id 995190
2024-03-28 22:02:24,971 - INFO - New GeoJSON for tile_id 995190 saved
2024-03-28 22:02:26,003 - INFO - Start processing tile_id 25175
2024-03-28 22:06:00,199 - INFO - New GeoJSON for tile_id 25175 saved
2024-03-28 22:06:00,686 - INFO - Start processing tile_id 50160
2024-03-28 22:10:25,357 - INFO - New GeoJSON for tile_id 50160 saved
2024-03-28 22:10:25,949 - INFO - Start processing tile_id 30175
2024-03-28 22:13:44,652 - INFO - New GeoJSON for tile_id 30175 saved
2024-03-28 22:13:45,075 - INFO - Start processing tile_id 47185
2024-03-28 22:18:44,474 - INFO - New GeoJSON for tile_id 47185 saved
2024-03-28 22:18:45,492 - INFO - Start processing tile_id 15205
2024-03-28 22:25:35,757 - INFO - New GeoJSON for tile_id 15205 saved
2024-03-28 22:25:36,350 - INFO - Start processing tile_id 17210
2024-03-28 22:31:10,967 - INFO - New GeoJSON for tile_id 17210 saved
2024-03-28 22:31:11,531 - INFO - Start processing tile_id 42240
2024-03-28 22:31:11,600 - INFO - Lidar Json data does not exist for tile 42240 in year 2017
2024-03-28 22:31:11,600 - INFO - Start processing tile_id 927122
2024-03-28 22:31:11,620 - INFO - Lidar Json data does not exist for tile 927122 in year 2017
2024-03-28 22:31:11,620 - INFO - Start processing tile_id 10267
2024-03-28 22:36:28,925 - INFO - New GeoJSON for tile_id 10267 saved
2024-03-28 22:36:30,402 - INFO - Start processing tile_id 55197
2024-03-28 22:42:45,017 - INFO - New GeoJSON for tile_id 55197 saved
2024-03-28 22:42:45,558 - INFO - Start processing tile_id 932165
2024-03-28 22:42:45,616 - INFO - Lidar Json data does not exist for tile 932165 in year 2017
2024-03-28 22:42:45,616 - INFO - Start processing tile_id 955150
2024-03-28 22:46:39,835 - INFO - New GeoJSON for tile_id 955150 saved
2024-03-28 22:46:40,699 - INFO - Start processing tile_id 35237
2024-03-28 22:51:26,908 - INFO - New GeoJSON for tile_id 35237 saved
2024-03-28 22:51:27,733 - INFO - Start processing tile_id 40177
2024-03-28 22:51:27,792 - INFO - Lidar Json data does not exist for tile 40177 in year 2017
2024-03-28 22:51:27,792 - INFO - Start processing tile_id 10215
2024-03-28 22:56:26,736 - INFO - New GeoJSON for tile_id 10215 saved
2024-03-28 22:56:27,648 - INFO - Start processing tile_id 940157
2024-03-28 23:08:07,515 - ERROR - Error processing tile_id: 940157. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-28 23:08:09,445 - INFO - Start processing tile_id 927135
2024-03-28 23:12:07,910 - INFO - New GeoJSON for tile_id 927135 saved
2024-03-28 23:12:08,432 - INFO - Start processing tile_id 170
2024-03-28 23:16:54,842 - INFO - New GeoJSON for tile_id 170 saved
2024-03-28 23:16:55,442 - INFO - Start processing tile_id 975190
2024-03-28 23:16:55,506 - INFO - Lidar Json data does not exist for tile 975190 in year 2017
2024-03-28 23:16:55,506 - INFO - Start processing tile_id 915140
2024-03-28 23:16:55,523 - INFO - Lidar Json data does not exist for tile 915140 in year 2017
2024-03-28 23:16:55,523 - INFO - Start processing tile_id 45242
2024-03-28 23:16:55,569 - INFO - Lidar Json data does not exist for tile 45242 in year 2017
2024-03-28 23:16:55,570 - INFO - Start processing tile_id 255
2024-03-28 23:16:55,586 - INFO - Lidar Json data does not exist for tile 255 in year 2017
2024-03-28 23:16:55,586 - INFO - Start processing tile_id 920142
2024-03-28 23:16:55,604 - INFO - Lidar Json data does not exist for tile 920142 in year 2017
2024-03-28 23:16:55,604 - INFO - Start processing tile_id 5190
2024-03-28 23:22:32,970 - INFO - New GeoJSON for tile_id 5190 saved
2024-03-28 23:22:33,618 - INFO - Start processing tile_id 42212
2024-03-28 23:28:48,982 - INFO - New GeoJSON for tile_id 42212 saved
2024-03-28 23:28:49,832 - INFO - Start processing tile_id 15257
2024-03-28 23:33:49,037 - INFO - New GeoJSON for tile_id 15257 saved
2024-03-28 23:33:49,660 - INFO - Start processing tile_id 955162
2024-03-28 23:38:48,305 - INFO - New GeoJSON for tile_id 955162 saved
2024-03-28 23:38:49,290 - INFO - Start processing tile_id 20262
2024-03-28 23:45:38,883 - INFO - New GeoJSON for tile_id 20262 saved
2024-03-28 23:45:40,320 - INFO - Start processing tile_id 40252
2024-03-28 23:50:23,016 - ERROR - Error processing tile_id: 40252. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-28 23:50:23,778 - INFO - Start processing tile_id 5187
2024-03-28 23:56:40,353 - INFO - New GeoJSON for tile_id 5187 saved
2024-03-28 23:56:41,204 - INFO - Start processing tile_id 42205
2024-03-29 00:04:29,807 - INFO - New GeoJSON for tile_id 42205 saved
2024-03-29 00:04:30,691 - INFO - Start processing tile_id 17177
2024-03-29 00:07:34,682 - INFO - New GeoJSON for tile_id 17177 saved
2024-03-29 00:07:35,169 - INFO - Start processing tile_id 7202
2024-03-29 00:10:05,744 - INFO - New GeoJSON for tile_id 7202 saved
2024-03-29 00:10:05,988 - INFO - Start processing tile_id 10237
2024-03-29 00:15:34,356 - INFO - New GeoJSON for tile_id 10237 saved
2024-03-29 00:15:35,148 - INFO - Start processing tile_id 40162
2024-03-29 00:15:35,206 - INFO - Lidar Json data does not exist for tile 40162 in year 2017
2024-03-29 00:15:35,207 - INFO - Start processing tile_id 935175
2024-03-29 00:15:35,225 - INFO - Lidar Json data does not exist for tile 935175 in year 2017
2024-03-29 00:15:35,226 - INFO - Start processing tile_id 932125
2024-03-29 00:15:35,242 - INFO - Lidar Json data does not exist for tile 932125 in year 2017
2024-03-29 00:15:35,242 - INFO - Start processing tile_id 987177
2024-03-29 00:21:51,942 - INFO - New GeoJSON for tile_id 987177 saved
2024-03-29 00:21:52,600 - INFO - Start processing tile_id 987182
2024-03-29 00:29:10,964 - INFO - New GeoJSON for tile_id 987182 saved
2024-03-29 00:29:11,777 - INFO - Start processing tile_id 982170
2024-03-29 00:34:35,595 - INFO - New GeoJSON for tile_id 982170 saved
2024-03-29 00:34:36,156 - INFO - Start processing tile_id 52222
2024-03-29 00:37:55,942 - INFO - New GeoJSON for tile_id 52222 saved
2024-03-29 00:37:56,520 - INFO - Start processing tile_id 15255
2024-03-29 00:42:15,806 - INFO - New GeoJSON for tile_id 15255 saved
2024-03-29 00:42:16,641 - INFO - Start processing tile_id 57175
2024-03-29 00:44:50,328 - INFO - New GeoJSON for tile_id 57175 saved
2024-03-29 00:44:50,793 - INFO - Start processing tile_id 10272
2024-03-29 00:45:14,017 - ERROR - Error processing tile_id: 10272. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-29 00:45:14,067 - INFO - Start processing tile_id 947162
2024-03-29 00:50:24,185 - INFO - New GeoJSON for tile_id 947162 saved
2024-03-29 00:50:25,071 - INFO - Start processing tile_id 980152
2024-03-29 00:50:25,137 - INFO - Lidar Json data does not exist for tile 980152 in year 2017
2024-03-29 00:50:25,138 - INFO - Start processing tile_id 945152
2024-03-29 00:59:38,296 - ERROR - Error processing tile_id: 945152. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-29 00:59:39,807 - INFO - Start processing tile_id 40240
2024-03-29 00:59:39,880 - INFO - Lidar Json data does not exist for tile 40240 in year 2017
2024-03-29 00:59:39,880 - INFO - Start processing tile_id 37150
2024-03-29 00:59:39,896 - INFO - Lidar Json data does not exist for tile 37150 in year 2017
2024-03-29 00:59:39,897 - INFO - Start processing tile_id 45177
2024-03-29 00:59:39,912 - INFO - Lidar Json data does not exist for tile 45177 in year 2017
2024-03-29 00:59:39,912 - INFO - Start processing tile_id 30230
2024-03-29 00:59:39,930 - INFO - Lidar Json data does not exist for tile 30230 in year 2017
2024-03-29 00:59:39,930 - INFO - Start processing tile_id 17167
2024-03-29 00:59:39,944 - INFO - Lidar Json data does not exist for tile 17167 in year 2017
2024-03-29 00:59:39,945 - INFO - Start processing tile_id 32240
2024-03-29 01:04:23,625 - INFO - New GeoJSON for tile_id 32240 saved
2024-03-29 01:04:24,300 - INFO - Start processing tile_id 7250
2024-03-29 01:09:11,992 - INFO - New GeoJSON for tile_id 7250 saved
2024-03-29 01:09:13,080 - INFO - Start processing tile_id 950137
2024-03-29 01:11:35,546 - ERROR - Error processing tile_id: 950137. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-29 01:11:35,931 - INFO - Start processing tile_id 5232
2024-03-29 01:18:17,151 - INFO - New GeoJSON for tile_id 5232 saved
2024-03-29 01:18:18,610 - INFO - Start processing tile_id 925125
2024-03-29 01:23:22,028 - INFO - New GeoJSON for tile_id 925125 saved
2024-03-29 01:23:22,868 - INFO - Start processing tile_id 945172
2024-03-29 01:24:05,136 - INFO - New GeoJSON for tile_id 945172 saved
2024-03-29 01:24:05,264 - INFO - Start processing tile_id 42260
2024-03-29 01:24:05,319 - INFO - Lidar Json data does not exist for tile 42260 in year 2017
2024-03-29 01:24:05,319 - INFO - Start processing tile_id 60207
2024-03-29 01:30:37,214 - INFO - New GeoJSON for tile_id 60207 saved
2024-03-29 01:30:37,885 - INFO - Start processing tile_id 15172
2024-03-29 01:35:03,375 - INFO - New GeoJSON for tile_id 15172 saved
2024-03-29 01:35:04,108 - INFO - Start processing tile_id 50162
2024-03-29 01:38:04,717 - ERROR - Error processing tile_id: 50162. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-29 01:38:05,156 - INFO - Start processing tile_id 25145
2024-03-29 01:38:05,219 - INFO - Lidar Json data does not exist for tile 25145 in year 2017
2024-03-29 01:38:05,219 - INFO - Start processing tile_id 240
2024-03-29 01:39:55,308 - ERROR - Error reading ProcessedLasData/Sept17th-2023/240/2017/JSON_TreeData_240/240_2017_ID_1_TreeCluster.json for tile 240: Expecting ',' delimiter: line 1 column 323585 (char 323584)
2024-03-29 01:43:49,368 - INFO - New GeoJSON for tile_id 240 saved
2024-03-29 01:43:50,872 - INFO - Start processing tile_id 12257
2024-03-29 01:43:50,931 - INFO - Lidar Json data does not exist for tile 12257 in year 2017
2024-03-29 01:43:50,931 - INFO - Start processing tile_id 12265
2024-03-29 01:53:24,035 - INFO - New GeoJSON for tile_id 12265 saved
2024-03-29 01:53:26,000 - INFO - Start processing tile_id 965167
2024-03-29 01:53:26,056 - INFO - Lidar Json data does not exist for tile 965167 in year 2017
2024-03-29 01:53:26,056 - INFO - Start processing tile_id 20157
2024-03-29 01:53:26,073 - INFO - Lidar Json data does not exist for tile 20157 in year 2017
2024-03-29 01:53:26,074 - INFO - Start processing tile_id 982197
2024-03-29 01:57:53,635 - INFO - New GeoJSON for tile_id 982197 saved
2024-03-29 01:57:55,357 - INFO - Start processing tile_id 990182
2024-03-29 02:04:19,023 - INFO - New GeoJSON for tile_id 990182 saved
2024-03-29 02:04:20,032 - INFO - Start processing tile_id 7217
2024-03-29 02:08:32,645 - INFO - New GeoJSON for tile_id 7217 saved
2024-03-29 02:08:33,361 - INFO - Start processing tile_id 955137
2024-03-29 02:08:33,421 - INFO - Lidar Json data does not exist for tile 955137 in year 2017
2024-03-29 02:08:33,421 - INFO - Start processing tile_id 952135
2024-03-29 02:08:33,437 - INFO - Lidar Json data does not exist for tile 952135 in year 2017
2024-03-29 02:08:33,437 - INFO - Start processing tile_id 935150
2024-03-29 02:10:31,606 - INFO - New GeoJSON for tile_id 935150 saved
2024-03-29 02:10:32,049 - INFO - Start processing tile_id 12232
2024-03-29 02:11:54,595 - INFO - New GeoJSON for tile_id 12232 saved
2024-03-29 02:11:54,766 - INFO - Start processing tile_id 5240
2024-03-29 02:17:11,318 - INFO - New GeoJSON for tile_id 5240 saved
2024-03-29 02:17:12,075 - INFO - Start processing tile_id 987210
2024-03-29 02:27:04,126 - INFO - New GeoJSON for tile_id 987210 saved
2024-03-29 02:27:05,395 - INFO - Start processing tile_id 32182
2024-03-29 02:33:04,274 - INFO - New GeoJSON for tile_id 32182 saved
2024-03-29 02:33:04,929 - INFO - Start processing tile_id 937137
2024-03-29 02:37:25,710 - INFO - New GeoJSON for tile_id 937137 saved
2024-03-29 02:37:26,539 - INFO - Start processing tile_id 982160
2024-03-29 02:41:19,849 - INFO - New GeoJSON for tile_id 982160 saved
2024-03-29 02:41:20,273 - INFO - Start processing tile_id 2142
2024-03-29 02:42:08,390 - ERROR - Error processing tile_id: 2142. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-29 02:42:08,721 - INFO - Start processing tile_id 45152
2024-03-29 02:42:08,785 - INFO - Lidar Json data does not exist for tile 45152 in year 2017
2024-03-29 02:42:08,786 - INFO - Start processing tile_id 995242
2024-03-29 02:42:08,805 - INFO - Lidar Json data does not exist for tile 995242 in year 2017
2024-03-29 02:42:08,805 - INFO - Start processing tile_id 950175
2024-03-29 02:42:27,011 - ERROR - Error processing tile_id: 950175. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-29 02:42:27,041 - INFO - Start processing tile_id 60215
2024-03-29 02:50:04,343 - INFO - New GeoJSON for tile_id 60215 saved
2024-03-29 02:50:05,375 - INFO - Start processing tile_id 937142
2024-03-29 02:51:31,960 - INFO - New GeoJSON for tile_id 937142 saved
2024-03-29 02:51:32,305 - INFO - Start processing tile_id 972162
2024-03-29 02:54:31,340 - INFO - New GeoJSON for tile_id 972162 saved
2024-03-29 02:54:31,958 - INFO - Start processing tile_id 10262
2024-03-29 02:59:51,360 - INFO - New GeoJSON for tile_id 10262 saved
2024-03-29 02:59:52,850 - INFO - Start processing tile_id 42160
2024-03-29 02:59:52,917 - INFO - Lidar Json data does not exist for tile 42160 in year 2017
2024-03-29 02:59:52,918 - INFO - Start processing tile_id 10187
2024-03-29 03:05:26,073 - INFO - New GeoJSON for tile_id 10187 saved
2024-03-29 03:05:26,967 - INFO - Start processing tile_id 5140
2024-03-29 03:06:13,842 - ERROR - Error processing tile_id: 5140. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-29 03:06:13,935 - INFO - Start processing tile_id 987172
2024-03-29 03:11:06,931 - INFO - New GeoJSON for tile_id 987172 saved
2024-03-29 03:11:07,433 - INFO - Start processing tile_id 45247
2024-03-29 03:11:30,717 - ERROR - Error processing tile_id: 45247. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-29 03:11:30,761 - INFO - Start processing tile_id 20200
2024-03-29 03:18:44,752 - INFO - New GeoJSON for tile_id 20200 saved
2024-03-29 03:18:45,452 - INFO - Start processing tile_id 15262
2024-03-29 03:29:25,371 - INFO - New GeoJSON for tile_id 15262 saved
2024-03-29 03:29:27,239 - INFO - Start processing tile_id 55162
2024-03-29 03:29:27,307 - INFO - Lidar Json data does not exist for tile 55162 in year 2017
2024-03-29 03:29:27,308 - INFO - Start processing tile_id 15237
2024-03-29 03:32:13,019 - INFO - New GeoJSON for tile_id 15237 saved
2024-03-29 03:32:13,433 - INFO - Start processing tile_id 942150
2024-03-29 03:43:30,426 - INFO - New GeoJSON for tile_id 942150 saved
2024-03-29 03:43:32,050 - INFO - Start processing tile_id 25265
2024-03-29 03:48:41,017 - INFO - New GeoJSON for tile_id 25265 saved
2024-03-29 03:48:41,672 - INFO - Start processing tile_id 922125
2024-03-29 03:55:04,574 - ERROR - Error processing tile_id: 922125. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-29 03:55:05,798 - INFO - Start processing tile_id 57197
2024-03-29 04:00:18,387 - INFO - New GeoJSON for tile_id 57197 saved
2024-03-29 04:00:18,926 - INFO - Start processing tile_id 950160
2024-03-29 04:05:31,283 - INFO - New GeoJSON for tile_id 950160 saved
2024-03-29 04:05:31,935 - INFO - Start processing tile_id 937170
2024-03-29 04:10:41,422 - INFO - New GeoJSON for tile_id 937170 saved
2024-03-29 04:10:42,224 - INFO - Start processing tile_id 935132
2024-03-29 04:24:52,157 - INFO - New GeoJSON for tile_id 935132 saved
2024-03-29 04:24:54,371 - INFO - Start processing tile_id 27190
2024-03-29 04:31:37,830 - INFO - New GeoJSON for tile_id 27190 saved
2024-03-29 04:31:38,552 - INFO - Start processing tile_id 10192
2024-03-29 04:38:06,177 - INFO - New GeoJSON for tile_id 10192 saved
2024-03-29 04:38:06,705 - INFO - Start processing tile_id 27227
2024-03-29 04:42:26,847 - INFO - New GeoJSON for tile_id 27227 saved
2024-03-29 04:42:27,358 - INFO - Start processing tile_id 60210
2024-03-29 04:46:57,837 - INFO - New GeoJSON for tile_id 60210 saved
2024-03-29 04:46:58,489 - INFO - Start processing tile_id 940145
2024-03-29 04:46:58,563 - INFO - Lidar Json data does not exist for tile 940145 in year 2017
2024-03-29 04:46:58,564 - INFO - Start processing tile_id 15240
2024-03-29 04:50:12,033 - INFO - New GeoJSON for tile_id 15240 saved
2024-03-29 04:50:12,510 - INFO - Start processing tile_id 235
2024-03-29 04:57:26,529 - INFO - New GeoJSON for tile_id 235 saved
2024-03-29 04:57:28,429 - INFO - Start processing tile_id 2137
2024-03-29 04:57:28,493 - INFO - Lidar Json data does not exist for tile 2137 in year 2017
2024-03-29 04:57:28,493 - INFO - Start processing tile_id 930135
2024-03-29 05:01:51,785 - INFO - New GeoJSON for tile_id 930135 saved
2024-03-29 05:01:52,573 - INFO - Start processing tile_id 977150
2024-03-29 05:01:52,647 - INFO - Lidar Json data does not exist for tile 977150 in year 2017
2024-03-29 05:01:52,648 - INFO - Start processing tile_id 970155
2024-03-29 05:01:52,665 - INFO - Lidar Json data does not exist for tile 970155 in year 2017
2024-03-29 05:01:52,666 - INFO - Start processing tile_id 992160
2024-03-29 05:07:22,057 - INFO - New GeoJSON for tile_id 992160 saved
2024-03-29 05:07:22,780 - INFO - Start processing tile_id 960145
2024-03-29 05:07:22,851 - INFO - Lidar Json data does not exist for tile 960145 in year 2017
2024-03-29 05:07:22,851 - INFO - Start processing tile_id 40260
2024-03-29 05:17:30,246 - ERROR - Error processing tile_id: 40260. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-29 05:17:31,237 - INFO - Start processing tile_id 2207
2024-03-29 05:21:18,351 - INFO - New GeoJSON for tile_id 2207 saved
2024-03-29 05:21:18,959 - INFO - Start processing tile_id 42162
2024-03-29 05:21:19,022 - INFO - Lidar Json data does not exist for tile 42162 in year 2017
2024-03-29 05:21:19,023 - INFO - Start processing tile_id 22262
2024-03-29 05:25:37,143 - INFO - New GeoJSON for tile_id 22262 saved
2024-03-29 05:25:37,667 - INFO - Start processing tile_id 35195
2024-03-29 05:30:40,266 - INFO - New GeoJSON for tile_id 35195 saved
2024-03-29 05:30:40,690 - INFO - Start processing tile_id 22165
2024-03-29 05:30:40,748 - INFO - Lidar Json data does not exist for tile 22165 in year 2017
2024-03-29 05:30:40,748 - INFO - Start processing tile_id 25252
2024-03-29 05:36:30,253 - INFO - New GeoJSON for tile_id 25252 saved
2024-03-29 05:36:31,055 - INFO - Start processing tile_id 910125
2024-03-29 05:36:31,114 - INFO - Lidar Json data does not exist for tile 910125 in year 2017
2024-03-29 05:36:31,115 - INFO - Start processing tile_id 27175
2024-03-29 05:40:48,318 - INFO - New GeoJSON for tile_id 27175 saved
2024-03-29 05:40:48,892 - INFO - Start processing tile_id 960170
2024-03-29 05:48:11,065 - INFO - New GeoJSON for tile_id 960170 saved
2024-03-29 05:48:12,189 - INFO - Start processing tile_id 987185
2024-03-29 05:52:54,671 - INFO - New GeoJSON for tile_id 987185 saved
2024-03-29 05:52:55,227 - INFO - Start processing tile_id 7192
2024-03-29 05:57:33,982 - INFO - New GeoJSON for tile_id 7192 saved
2024-03-29 05:57:34,482 - INFO - Start processing tile_id 17267
2024-03-29 06:06:45,401 - ERROR - Error processing tile_id: 17267. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-29 06:06:46,690 - INFO - Start processing tile_id 55195
2024-03-29 06:13:22,665 - INFO - New GeoJSON for tile_id 55195 saved
2024-03-29 06:13:23,310 - INFO - Start processing tile_id 22257
2024-03-29 06:17:57,024 - INFO - New GeoJSON for tile_id 22257 saved
2024-03-29 06:17:57,525 - INFO - Start processing tile_id 42235
2024-03-29 06:17:57,590 - INFO - Lidar Json data does not exist for tile 42235 in year 2017
2024-03-29 06:17:57,590 - INFO - Start processing tile_id 930170
2024-03-29 06:20:11,905 - ERROR - Error processing tile_id: 930170. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-29 06:20:12,401 - INFO - Start processing tile_id 977145
2024-03-29 06:20:12,463 - INFO - Lidar Json data does not exist for tile 977145 in year 2017
2024-03-29 06:20:12,463 - INFO - Start processing tile_id 940165
2024-03-29 06:25:04,572 - INFO - New GeoJSON for tile_id 940165 saved
2024-03-29 06:25:05,518 - INFO - Start processing tile_id 982205
2024-03-29 06:30:13,746 - INFO - New GeoJSON for tile_id 982205 saved
2024-03-29 06:30:15,518 - INFO - Start processing tile_id 2222
2024-03-29 06:31:04,440 - ERROR - Error reading ProcessedLasData/Sept17th-2023/2222/2017/JSON_TreeData_2222/2222_2017_ID_3_TreeCluster.json for tile 2222: Expecting ',' delimiter: line 1 column 3932161 (char 3932160)
2024-03-29 06:33:32,351 - INFO - New GeoJSON for tile_id 2222 saved
2024-03-29 06:33:32,955 - INFO - Start processing tile_id 977155
2024-03-29 06:33:33,014 - INFO - Lidar Json data does not exist for tile 977155 in year 2017
2024-03-29 06:33:33,015 - INFO - Start processing tile_id 930132
2024-03-29 06:39:43,042 - INFO - New GeoJSON for tile_id 930132 saved
2024-03-29 06:39:44,219 - INFO - Start processing tile_id 15215
2024-03-29 06:45:30,112 - INFO - New GeoJSON for tile_id 15215 saved
2024-03-29 06:45:30,860 - INFO - Start processing tile_id 12160
2024-03-29 06:48:27,295 - ERROR - Error processing tile_id: 12160. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-29 06:48:27,840 - INFO - Start processing tile_id 5200
2024-03-29 06:50:54,373 - INFO - New GeoJSON for tile_id 5200 saved
2024-03-29 06:50:54,663 - INFO - Start processing tile_id 27262
2024-03-29 06:56:09,667 - INFO - New GeoJSON for tile_id 27262 saved
2024-03-29 06:56:10,611 - INFO - Start processing tile_id 47177
2024-03-29 06:58:06,795 - INFO - New GeoJSON for tile_id 47177 saved
2024-03-29 06:58:06,992 - INFO - Start processing tile_id 12177
2024-03-29 07:01:33,738 - INFO - New GeoJSON for tile_id 12177 saved
2024-03-29 07:01:34,357 - INFO - Start processing tile_id 2175
2024-03-29 07:06:05,647 - INFO - New GeoJSON for tile_id 2175 saved
2024-03-29 07:06:06,093 - INFO - Start processing tile_id 962155
2024-03-29 07:11:17,699 - INFO - New GeoJSON for tile_id 962155 saved
2024-03-29 07:11:18,494 - INFO - Start processing tile_id 935155
2024-03-29 07:22:25,584 - ERROR - Error processing tile_id: 935155. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-29 07:22:27,541 - INFO - Start processing tile_id 27180
2024-03-29 07:27:06,337 - INFO - New GeoJSON for tile_id 27180 saved
2024-03-29 07:27:06,957 - INFO - Start processing tile_id 22195
2024-03-29 07:35:17,593 - INFO - New GeoJSON for tile_id 22195 saved
2024-03-29 07:35:18,745 - INFO - Start processing tile_id 17202
2024-03-29 07:42:25,441 - INFO - New GeoJSON for tile_id 17202 saved
2024-03-29 07:42:26,018 - INFO - Start processing tile_id 12157
2024-03-29 07:45:21,298 - ERROR - Error processing tile_id: 12157. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-29 07:45:22,089 - INFO - Start processing tile_id 12252
2024-03-29 07:48:29,691 - INFO - New GeoJSON for tile_id 12252 saved
2024-03-29 07:48:30,133 - INFO - Start processing tile_id 22185
2024-03-29 07:54:47,260 - INFO - New GeoJSON for tile_id 22185 saved
2024-03-29 07:54:47,897 - INFO - Start processing tile_id 42190
2024-03-29 08:00:26,015 - INFO - New GeoJSON for tile_id 42190 saved
2024-03-29 08:00:26,701 - INFO - Start processing tile_id 917137
2024-03-29 08:07:09,587 - ERROR - Error processing tile_id: 917137. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-29 08:07:10,798 - INFO - Start processing tile_id 50225
2024-03-29 08:07:10,863 - INFO - Lidar Json data does not exist for tile 50225 in year 2017
2024-03-29 08:07:10,863 - INFO - Start processing tile_id 2167
2024-03-29 08:11:46,474 - INFO - New GeoJSON for tile_id 2167 saved
2024-03-29 08:11:47,287 - INFO - Start processing tile_id 5165
2024-03-29 08:16:48,818 - INFO - New GeoJSON for tile_id 5165 saved
2024-03-29 08:16:49,833 - INFO - Start processing tile_id 970190
2024-03-29 08:16:49,893 - INFO - Lidar Json data does not exist for tile 970190 in year 2017
2024-03-29 08:16:49,893 - INFO - Start processing tile_id 137
2024-03-29 08:16:49,911 - INFO - Lidar Json data does not exist for tile 137 in year 2017
2024-03-29 08:16:49,911 - INFO - Start processing tile_id 45195
2024-03-29 08:19:05,101 - INFO - New GeoJSON for tile_id 45195 saved
2024-03-29 08:19:05,547 - INFO - Start processing tile_id 25242
2024-03-29 08:23:08,061 - INFO - New GeoJSON for tile_id 25242 saved
2024-03-29 08:23:08,592 - INFO - Start processing tile_id 912137
2024-03-29 08:23:08,656 - INFO - Lidar Json data does not exist for tile 912137 in year 2017
2024-03-29 08:23:08,656 - INFO - Start processing tile_id 50250
2024-03-29 08:23:08,671 - INFO - Lidar Json data does not exist for tile 50250 in year 2017
2024-03-29 08:23:08,671 - INFO - Start processing tile_id 960137
2024-03-29 08:23:08,709 - INFO - Lidar Json data does not exist for tile 960137 in year 2017
2024-03-29 08:23:08,709 - INFO - Start processing tile_id 985162
2024-03-29 08:27:53,009 - INFO - New GeoJSON for tile_id 985162 saved
2024-03-29 08:27:53,532 - INFO - Start processing tile_id 35180
2024-03-29 08:30:23,829 - INFO - New GeoJSON for tile_id 35180 saved
2024-03-29 08:30:24,176 - INFO - Start processing tile_id 915130
2024-03-29 08:30:24,238 - INFO - Lidar Json data does not exist for tile 915130 in year 2017
2024-03-29 08:30:24,239 - INFO - Start processing tile_id 25207
2024-03-29 08:35:31,541 - INFO - New GeoJSON for tile_id 25207 saved
2024-03-29 08:35:32,246 - INFO - Start processing tile_id 12262
2024-03-29 08:40:20,396 - INFO - New GeoJSON for tile_id 12262 saved
2024-03-29 08:40:21,707 - INFO - Start processing tile_id 52190
2024-03-29 08:45:11,298 - INFO - New GeoJSON for tile_id 52190 saved
2024-03-29 08:45:11,989 - INFO - Start processing tile_id 42255
2024-03-29 08:47:26,540 - ERROR - Error processing tile_id: 42255. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-29 08:47:27,084 - INFO - Start processing tile_id 985167
2024-03-29 08:53:59,151 - INFO - New GeoJSON for tile_id 985167 saved
2024-03-29 08:53:59,840 - INFO - Start processing tile_id 912132
2024-03-29 08:53:59,913 - INFO - Lidar Json data does not exist for tile 912132 in year 2017
2024-03-29 08:53:59,914 - INFO - Start processing tile_id 962152
2024-03-29 08:59:05,726 - INFO - New GeoJSON for tile_id 962152 saved
2024-03-29 08:59:06,727 - INFO - Start processing tile_id 40172
2024-03-29 08:59:06,790 - INFO - Lidar Json data does not exist for tile 40172 in year 2017
2024-03-29 08:59:06,791 - INFO - Start processing tile_id 35222
2024-03-29 09:04:35,755 - INFO - New GeoJSON for tile_id 35222 saved
2024-03-29 09:04:36,286 - INFO - Start processing tile_id 50215
2024-03-29 09:12:30,114 - INFO - New GeoJSON for tile_id 50215 saved
2024-03-29 09:12:31,527 - INFO - Start processing tile_id 42230
2024-03-29 09:12:31,591 - INFO - Lidar Json data does not exist for tile 42230 in year 2017
2024-03-29 09:12:31,591 - INFO - Start processing tile_id 2155
2024-03-29 09:16:19,142 - INFO - New GeoJSON for tile_id 2155 saved
2024-03-29 09:16:19,880 - INFO - Start processing tile_id 952160
2024-03-29 09:24:35,363 - INFO - New GeoJSON for tile_id 952160 saved
2024-03-29 09:24:36,619 - INFO - Start processing tile_id 65205
2024-03-29 09:28:31,951 - INFO - New GeoJSON for tile_id 65205 saved
2024-03-29 09:28:32,368 - INFO - Start processing tile_id 985155
2024-03-29 09:32:04,634 - INFO - New GeoJSON for tile_id 985155 saved
2024-03-29 09:32:05,104 - INFO - Start processing tile_id 927160
2024-03-29 09:33:54,722 - ERROR - Error processing tile_id: 927160. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-29 09:33:55,081 - INFO - Start processing tile_id 952140
2024-03-29 09:35:23,121 - INFO - New GeoJSON for tile_id 952140 saved
2024-03-29 09:35:23,453 - INFO - Start processing tile_id 987145
2024-03-29 09:35:23,526 - INFO - Lidar Json data does not exist for tile 987145 in year 2017
2024-03-29 09:35:23,526 - INFO - Start processing tile_id 945155
2024-03-29 09:41:59,610 - INFO - New GeoJSON for tile_id 945155 saved
2024-03-29 09:42:00,907 - INFO - Start processing tile_id 972142
2024-03-29 09:42:00,982 - INFO - Lidar Json data does not exist for tile 972142 in year 2017
2024-03-29 09:42:00,983 - INFO - Start processing tile_id 990172
2024-03-29 09:47:53,705 - INFO - New GeoJSON for tile_id 990172 saved
2024-03-29 09:47:54,417 - INFO - Start processing tile_id 972177
2024-03-29 09:47:54,493 - INFO - Lidar Json data does not exist for tile 972177 in year 2017
2024-03-29 09:47:54,493 - INFO - Start processing tile_id 17180
2024-03-29 09:50:35,417 - INFO - New GeoJSON for tile_id 17180 saved
2024-03-29 09:50:35,788 - INFO - Start processing tile_id 925160
2024-03-29 09:50:35,844 - INFO - Lidar Json data does not exist for tile 925160 in year 2017
2024-03-29 09:50:35,844 - INFO - Start processing tile_id 32210
2024-03-29 09:56:13,047 - INFO - New GeoJSON for tile_id 32210 saved
2024-03-29 09:56:13,852 - INFO - Start processing tile_id 60217
2024-03-29 09:59:17,181 - INFO - New GeoJSON for tile_id 60217 saved
2024-03-29 09:59:17,702 - INFO - Start processing tile_id 27255
2024-03-29 10:03:42,670 - INFO - New GeoJSON for tile_id 27255 saved
2024-03-29 10:03:43,302 - INFO - Start processing tile_id 5262
2024-03-29 10:03:43,364 - INFO - Lidar Json data does not exist for tile 5262 in year 2017
2024-03-29 10:03:43,364 - INFO - Start processing tile_id 15182
2024-03-29 10:08:34,368 - INFO - New GeoJSON for tile_id 15182 saved
2024-03-29 10:08:35,123 - INFO - Start processing tile_id 975177
2024-03-29 10:08:35,191 - INFO - Lidar Json data does not exist for tile 975177 in year 2017
2024-03-29 10:08:35,191 - INFO - Start processing tile_id 977190
2024-03-29 10:11:56,961 - ERROR - Error processing tile_id: 977190. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-29 10:11:57,418 - INFO - Start processing tile_id 32160
2024-03-29 10:14:26,401 - INFO - New GeoJSON for tile_id 32160 saved
2024-03-29 10:14:27,410 - INFO - Start processing tile_id 35250
2024-03-29 10:15:03,466 - ERROR - Error processing tile_id: 35250. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-29 10:15:03,736 - INFO - Start processing tile_id 980207
2024-03-29 10:15:03,808 - INFO - Lidar Json data does not exist for tile 980207 in year 2017
2024-03-29 10:15:03,809 - INFO - Start processing tile_id 2140
2024-03-29 10:16:42,190 - ERROR - Error processing tile_id: 2140. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-29 10:16:42,538 - INFO - Start processing tile_id 52225
2024-03-29 10:16:42,604 - INFO - Lidar Json data does not exist for tile 52225 in year 2017
2024-03-29 10:16:42,605 - INFO - Start processing tile_id 940137
2024-03-29 10:20:20,195 - INFO - New GeoJSON for tile_id 940137 saved
2024-03-29 10:20:21,132 - INFO - Start processing tile_id 992170
2024-03-29 10:25:06,243 - INFO - New GeoJSON for tile_id 992170 saved
2024-03-29 10:25:07,072 - INFO - Start processing tile_id 2205
2024-03-29 10:29:11,158 - INFO - New GeoJSON for tile_id 2205 saved
2024-03-29 10:29:11,874 - INFO - Start processing tile_id 35155
2024-03-29 10:30:09,365 - ERROR - Error processing tile_id: 35155. Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "Scripts/IndexMatch_HL_aws1.py", line 524, in process_tile
    avg_dbh = get_avg_dbh(filtered_geojson_data)
  File "Scripts/IndexMatch_HL_aws1.py", line 250, in get_avg_dbh
    features = filter_geojson_data["features"]
TypeError: 'NoneType' object is not subscriptable
2024-03-29 10:30:09,595 - INFO - Start processing tile_id 947140
2024-03-29 10:33:52,612 - INFO - New GeoJSON for tile_id 947140 saved
2024-03-29 10:33:53,691 - INFO - Start processing tile_id 10270
2024-03-29 10:37:49,613 - INFO - New GeoJSON for tile_id 10270 saved
2024-03-29 10:37:50,924 - INFO - Start processing tile_id 42215
2024-03-29 10:43:37,606 - INFO - New GeoJSON for tile_id 42215 saved
2024-03-29 10:43:38,562 - INFO - Start processing tile_id 950130
2024-03-29 10:43:38,630 - INFO - Lidar Json data does not exist for tile 950130 in year 2017
2024-03-29 10:43:38,631 - INFO - Start processing tile_id 30265
2024-03-29 10:43:38,648 - INFO - Lidar Json data does not exist for tile 30265 in year 2017
2024-03-29 10:43:38,649 - INFO - Start processing tile_id 912130
2024-03-29 10:43:38,665 - INFO - Lidar Json data does not exist for tile 912130 in year 2017
2024-03-29 10:43:38,666 - INFO - Start processing tile_id 17215
2024-03-29 10:49:16,074 - INFO - New GeoJSON for tile_id 17215 saved
2024-03-29 10:49:16,682 - INFO - Start processing tile_id 992235
2024-03-29 10:51:38,260 - INFO - New GeoJSON for tile_id 992235 saved
2024-03-29 10:51:39,241 - INFO - Start processing tile_id 935160
2024-04-11 14:00:19,878 - INFO - Found credentials from IAM Role: treefolio-sylvania-ec2
2024-04-11 14:00:35,842 - INFO - Start processing tile_id 987177
2024-04-11 14:06:39,596 - INFO - New GeoJSON for tile_id 987177 saved
2024-04-11 14:06:40,246 - INFO - Start processing tile_id 987182
2024-04-11 14:13:35,360 - INFO - New GeoJSON for tile_id 987182 saved
2024-04-11 14:13:36,198 - INFO - Start processing tile_id 935160
2024-04-11 14:42:13,633 - INFO - Found credentials from IAM Role: treefolio-sylvania-ec2
2024-04-11 14:42:30,309 - INFO - Start processing tile_id 985152
2024-04-11 14:45:19,992 - INFO - Found credentials from IAM Role: treefolio-sylvania-ec2
2024-04-11 14:45:29,795 - INFO - Start processing tile_id 7245
2024-04-11 14:49:14,758 - INFO - New GeoJSON for tile_id 7245 saved
2024-04-11 14:49:15,455 - INFO - Start processing tile_id 60185
2024-04-11 14:50:50,889 - INFO - New GeoJSON for tile_id 60185 saved
2024-04-11 14:50:51,087 - INFO - Start processing tile_id 937152
